name: lint

on:
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm install

      - run: npm run format
      - run: npm run format:check

      - run: npm run lint:ls
      - run: npm run lint:md
